#!/usr/bin/env bash


ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.."


# exit on error
# echo on
set -e
set -x


cd "$ROOT_DIR"


# uninstall
yes | pyenv uninstall 3.8.1\@view.py


# create env
pyenv virtualenv 3.8.1 3.8.1\@view.py
